_target_: src.transforms.base.TransformWrapper
transform_fn: ${params.data.tokenizer}
mapping:
  text: text
transform_kwargs:
  padding: max_length
  truncation: true
  max_length: ${params.data.max_length}
  return_tensors: "pt"
