_target_: src.transforms.base.TransformWrapper
transform_fn:
  _target_: torchvision.transforms.ToTensor
mapping: ??? # override in parent config
is_elementwise: true
new_key: ??? # override in parent config
input_format: list
