version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "02:00"
    open-pull-requests-limit: 5
    assignees:
      - "Artem.Makoian"
    reviewers:
      - "Artem.Makoian"
    labels:
      - "dependencies"
    ignore:
      - dependency-name: "torch"
      - dependency-name: "lightning"
