repos:
  # Ruff: lint and format
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.9
    hooks:
      - id: ruff
        args: ["--fix"]
      - id: ruff-format

  # Mypy: static type checking
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.2
    hooks:
      - id: mypy
        args: ["--config-file", "mypy.ini"]
        additional_dependencies: []

  # Detect-secrets: baseline-backed secret scanning
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
      - id: detect-secrets
        name: detect-secrets (with baseline)
        args: ["--baseline", ".secrets.baseline"]
        exclude: |
          ^logs/|^data/|^node_modules/|^ml_core\.egg-info/

  # Gitleaks: secret scanning
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.18.4
    hooks:
      - id: gitleaks
        name: gitleaks (secrets)
        args:
          [
            "detect",
            "--no-banner",
            "--source",
            ".",
            "--report-format",
            "json",
            "--config",
            "gitleaks.toml",
          ]
        stages: [commit, push, manual]

  # Semgrep: security and correctness patterns
  - repo: https://github.com/returntocorp/semgrep
    rev: v1.82.0
    hooks:
      - id: semgrep
        args: ["--config=.semgrep.yml", "--severity=ERROR", "--error"]
        additional_dependencies: []
        exclude: |
          ^logs/|^data/|^node_modules/|^ml_core\.egg-info/

  # Bandit: Python security scanner
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.9
    hooks:
      - id: bandit
        args:
          [
            "-q",
            "-c",
            "bandit.yaml",
            "-s",
            "B101",
            "-x",
            "tests,logs,data,node_modules,ml_core.egg-info",
          ]
        types: [python]

  # Local hooks: import-linter, tests, and guard rails
  - repo: local
    hooks:
      - id: import-linter
        name: import-linter (architecture boundaries)
        entry: bash -lc "lint-imports --config=architecture/importlinter.ini"
        language: system
        pass_filenames: false
        stages: [commit, push, manual]

      - id: precommit-tests
        name: quick tests (not slow)
        entry: bash scripts/precommit_tests.sh
        language: system
        pass_filenames: false
        stages: [commit]

      - id: prevent-test-changes
        name: prevent unapproved test changes
        entry: bash scripts/prevent_test_changes.sh
        language: system
        pass_filenames: false
        stages: [commit, push]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      # list of supported hooks: https://pre-commit.com/hooks.html
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-docstring-first
      - id: check-yaml
      - id: debug-statements
      - id: detect-private-key
      - id: check-executables-have-shebangs
      - id: check-toml
      - id: check-case-conflict
      - id: check-added-large-files

  # python import sorting
  - repo: https://github.com/PyCQA/isort
    rev: 7.0.0
    hooks:
      - id: isort
        args: ["--profile", "black", "--filter-files"]

  # python upgrading syntax to newer version
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.21.0
    hooks:
      - id: pyupgrade
        args: [--py38-plus]

  # python docstring formatting
  - repo: https://github.com/myint/docformatter
    rev: v1.7.7
    hooks:
      - id: docformatter
        args:
          [
            --in-place,
            --wrap-summaries=99,
            --wrap-descriptions=99,
            --style=sphinx,
            --black,
          ]

  # python docstring coverage checking
  - repo: https://github.com/econchick/interrogate
    rev: 1.7.0 # or master if you're bold
    hooks:
      - id: interrogate
        args:
          [
            --verbose,
            --fail-under=60,
            --ignore-init-module,
            --ignore-init-method,
            --ignore-module,
            --ignore-nested-functions,
            -vv,
          ]
        additional_dependencies:
          - setuptools<81

  # python check (PEP8), programming errors and code complexity
  - repo: https://github.com/PyCQA/flake8
    rev: 7.3.0
    hooks:
      - id: flake8
        args:
          [
            "--extend-ignore",
            "E203,E402,E501,F401,F841,RST2,RST301",
            "--exclude",
            "logs/*,data/*",
          ]
        additional_dependencies: [flake8-rst-docstrings==0.3.0]

  # yaml formatting
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        types: [yaml]
        exclude: "environment.yaml"

  # shell scripts linter
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.11.0.1
    hooks:
      - id: shellcheck

  # md formatting
  - repo: https://github.com/executablebooks/mdformat
    rev: 0.7.17
    hooks:
      - id: mdformat
        args: ["--number"]
        additional_dependencies:
          - mdformat-gfm==0.4.1
          - mdformat-tables==0.4.0
          - mdformat_frontmatter==2.0.8
          # - mdformat-toc
          # - mdformat-black

  # word spelling linter
  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.1
    hooks:
      - id: codespell
        args:
          - --skip=logs/**,data/**,*.ipynb
          # - --ignore-words-list=abc,def

  # jupyter notebook cell output clearing
  - repo: https://github.com/kynan/nbstripout
    rev: 0.8.1
    hooks:
      - id: nbstripout

  # jupyter notebook linting
  - repo: https://github.com/nbQA-dev/nbQA
    rev: 1.9.1
    hooks:
      - id: nbqa-isort
        args: ["--profile=black"]
        additional_dependencies:
          - isort
          - setuptools<81
      - id: nbqa-flake8
        args:
          [
            "--extend-ignore=E203,E402,E501,F401,F841",
            "--exclude=logs/*,data/*",
          ]
        additional_dependencies:
          - flake8
          - setuptools<81

default_stages: [commit]

ci:
  autofix_prs: false
  skip: []
  autoupdate_schedule: quarterly
default_language_version:
  python: python3.11
