defaults:
  - /transforms/base@forward_fn.transforms.net: model_forward
  - /transforms/base@forward_fn.transforms.argmax: argmax

_target_: src.models.base_module.BaseLitModule

forward_fn:
  _target_: src.transforms.base.TransformCompose

criterion:
  ce:
    - logits: input
      label: target
    - _target_: torch.nn.CrossEntropyLoss

criterion_coefs:
  ce: 1.0

metrics:
  acc:
    - predictions: preds
      label: target
    - [train, val, test]
    - _target_: torchmetrics.Accuracy
      task: multiclass
      num_classes: 10

tracked_metric_mode: max
tracked_metric_name: acc

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.001
  weight_decay: 0.0

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 10

# compile model for faster training with pytorch 2.0
compile: false
