defaults:
  - /transforms/base@forward_fn.transforms.net: model_forward
  - /transforms/base@forward_fn.transforms.argmax: argmax
  - criterion: cross_entropy
  - metrics: accuracy

_target_: src.models.base_module.BaseLitModule

forward_fn:
  _target_: src.transforms.base.TransformCompose

criterion_coefs:
  cross_entropy: 1.0

tracked_metric_mode: max
tracked_metric_name: accuracy

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.001
  weight_decay: 0.0

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 10

# compile model for faster training with pytorch 2.0
compile: false
