_target_: src.models.base_module.BaseLitModule

forward_fn:
  _target_: src.transforms.base.TransformCompose
  transforms:
    net:
      _target_: src.transforms.base.TransformWrapper
      transform_fn:
        _target_: src.models.components.simple_dense_net.SimpleDenseNet
        input_size: 784
        lin1_size: 64
        lin2_size: 128
        lin3_size: 64
        output_size: 10
      mapping:
        image: x
      new_key: logits
    argmax:
      _target_: src.transforms.base.TransformWrapper
      transform_fn:
        _target_: torch.argmax
        _partial_: true
        dim: -1
      mapping:
        logits: input
      new_key: predictions

criterion:
  ce:
    - logits: input
      label: target
    - _target_: torch.nn.CrossEntropyLoss

criterion_coefs:
  ce: 1.0

metrics:
  acc:
    - predictions: preds
      label: target
    - [train, val, test]
    - _target_: torchmetrics.Accuracy
      task: multiclass
      num_classes: 10

tracked_metric_mode: max
tracked_metric_name: acc

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.001
  weight_decay: 0.0

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 10

# compile model for faster training with pytorch 2.0
compile: false
