defaults:
  - model_checkpoint
  - early_stopping
  - model_summary
  - rich_progress_bar
  - _self_

model_checkpoint:
  dirpath: ${paths.output_dir}/checkpoints
  filename: "epoch_{epoch:03d}"
  monitor: "val/${model.tracked_metric_name}"
  mode: ${model.tracked_metric_mode}
  save_last: True
  auto_insert_metric_name: False

early_stopping:
  monitor: "val/${model.tracked_metric_name}"
  patience: 100
  mode: ${model.tracked_metric_mode}

model_summary:
  max_depth: -1
