name: CI

on:
  pull_request:
  push:
    branches:
      - main
      - "*"

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_test_lint_security:
    name: Lint, type-check, test, security
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"
          cache-dependency-path: |
            requirements.txt
            requirements-dev.txt

      - name: Create venv and install dependencies
        run: |
          python -m venv .venv
          . .venv/bin/activate
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt -r requirements-dev.txt

      - name: Ruff check
        run: .venv/bin/ruff check .

      - name: Ruff format check
        run: .venv/bin/ruff format --check .

      - name: Mypy
        run: .venv/bin/mypy .

      - name: Pytest (not slow)
        run: .venv/bin/pytest -n auto -m "not slow" -q

      - name: Bandit security scan
        run: .venv/bin/bandit -r -q . -c bandit.yaml -x .venv

      - name: Semgrep scan
        env:
          SEMGREP_ENABLE_VERSION_CHECK: "0"
        run: .venv/bin/semgrep --config .semgrep.yml --error --exclude .venv

  secrets_scan:
    name: Gitleaks secrets scan
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: --config gitleaks.toml

  ai_review_optional:
    if: ${{ secrets.AI_REVIEW_API_KEY != '' }}
    name: AI review (optional)
    runs-on: ubuntu-latest
    steps:
      - run: echo "AI review would run here if configured."
